name: Ruby package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0-beta
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: Install requirements
      run: |
        bundle update --bundler
        bundle install
    - name: Run tests and collect coverage
      run: bundle exec rspec
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5.0.0-beta
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
